@startuml 
salt
{+
  [ Приєднатись до дискусії (FR2.1) ]
  ==
  ^Пошук Дискусії:^ | [Введіть тему або ID дискусії ]
  --
  <color:blue>Результати Пошуку (Активні/Публічні)</color>
  --
  {T#
  +Тема | Статус | Дія
  + <b>Дискусія А</b> | 45 учасників | [Приєднатись]
  + Дискусія B | Нова! 5 учасників | [Приєднатись]
  }
}
@enduml
