@startuml 
salt
{+
    {* Файл | Вигляд | Допомога }
    --
    {/ <b><color:black>Дискусії (FR2.1)</color> | <b>Створити Ідею (FR2.2) | <b>Ресурси (FR2.4) }
    --
    <color:blue><b>ПРОФЕСІЙНЕ СПІЛКУВАННЯ (FR2)</b></color>
    --
    |Список активних обговорень | [ Деталі Дискусії ]
    {T#
    +Тема Дискусії (ID)        | Остання активність     | Учасників
    + <color:black><b>Дискусія А (123)</b></color> | 1 хв тому (3 нових) | 5
    ++ Ідея 1.1 (FR2.2)       | -                      | -
    + Дискусія В (234)        | 3 год тому (0 нових) | 12
    }
    --
    {^"Новий Коментар (FR2.3)"
        "Введіть ваш коментар тут... "
        --
        [Надіслати коментар]
    }
}
@enduml
