@startuml 
salt
{+
    {* Файл | Вигляд | Допомога }
    --
    {/ <color:black>Дискусії (FR2.1)</color> | <b>Створити Ідею (FR2.2) | <color:black>Ресурси (FR2.4)</color> }
    --
    [ Надіслати нову наукову ідею (FR2.2) ]
    ==
    {#
    Заголовок ідеї: | "Введіть стислий заголовок  "
    --
    Опис (до 500 сим.): | {SI "Опишіть вашу ідею..."}
    --
    Приєднати до: | ^Нова Дискусія^ | ^Існуюча (ID: 123)^ | ^Приватна^
    }
    --
    [X] Зробити ідею приватною (доступно лише колегам)
    ==
    [ Надіслати ] | [ Скасувати ]
}
@enduml
